name: "🪄 Feature Request"
description: "Suggest an interesting feature idea for this project"
title: "🪄 Feature: "
labels: ["enhancement 🪄"]
assignees:
  - Witty-Wizard

body:
  - type: textarea
    id: problem-description
    attributes:
      label: "Is your feature request related to a problem? Please describe."
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
      placeholder: "Describe the problem..."
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."
      placeholder: "Describe the desired solution..."
    validations:
      required: true

  - type: textarea
    id: alternatives-description
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
      placeholder: "Describe alternative solutions..."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
      placeholder: "Add additional context..."
    validations:
      required: false
